---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: prometheus
    namespace: monitoring
spec:
    chart:
        spec:
            chart: ./charts/kube-prometheus-stack
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: GitRepository
                name: prometheus-helm
    values:
        grafana:
            ingress:
                enabled: true
                path: /grafana
    interval: 30m0s
