apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
    name: prometheus-helm
    namespace: monitoring
spec:
    interval: 30m0s
    ref:
        branch: main
    url: https://github.com/prometheus-community/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: prometheus
    namespace: monitoring
spec:
    chart:
        spec:
            chart: ./charts/kube-prometheus-stack
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: GitRepository
                name: prometheus-helm
    values:
        grafana:
            ingress:
                enabled: true
                path: /grafana
            grafana.ini:
                server:
                    domain: cluster-worker01.local
                    root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
                    serve_from_sub_path: true
        alertmanager:
            config:
                receivers:
                    - name: "null"
                    - name: "discord"
                      webhook_configs:
                          - send_resolved: true
                            url: "discord-alerthandler:8089"

    interval: 30m0s
