apiVersion: batch/v1
kind: CronJob
metadata:
    name: nordnet-fetch
    namespace: nordnet-fetch
spec:
    schedule: "0 0 * * 6"
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: nordnet-fetch
                          image: michaelbui99/nordnet-fetch
                          imagePullPolicy: Always
                    imagePullSecrets:
                        - name: docker-hub-cred
                    restartPolicy: OnFailure
